apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.http.serviceName | default .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ default .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.http.port | default 3000 }}
      targetPort: {{ .Values.http.port | default 3000 }}
      protocol: TCP
  type: {{ .Values.http.serviceType | default "ClusterIP" }}
